# Generated by Django 3.0.6 on 2020-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200528_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
